### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by omarbenk** [Elucidation/ChessboardDetect#3]
Hi, thanks for sharing your work!

Just wanted to ask, I get the No Files error, well due to not having the files linked. Do you know how I can the training data?

**Comment by peijason** [comment]
Yup... Where is your testing data?

**Comment by Elucidation** [comment]
Apologies, the intent of this repo was not to share the training/test data as it contains actual photos/images from the internet or in real life. 

One approach to building your own is to take a set of images with chessboards in them, manually find the chessboard edge points (or modify non-ML chessboard detection code in this repo to generate them), storing these points and passing into https://github.com/Elucidation/ChessboardDetect/blob/master/generateFullDataset.py to generate the chess tiles.

With modifications something like https://github.com/Elucidation/ChessboardDetect/blob/master/chessboard_detect2.py would allow you to find those points from images using classical CV techniques. Again, this is a very rough repository so you would likely have to make many changes and reverse engineer portions of this to get what you want.
